from machine_templates import sea_kakuhen_10r, sea_kakuhen_loop, sea_st_jitan
from machine_types import Machine, Payout

SEA_INITIAL_MACHINES = {
    # A-1. Pスーパー海物語IN沖縄6 (미들)
    "oki_sea_6": Machine(
        id="oki_sea_6",
        name_ja="Pスーパー海物語IN沖縄6",
        name_ko="P 슈퍼 바다이야기 IN 오키나와6",
        spec_type="미들 / 확변 루프 + ジンベェタイム",
        risk_grade="1/319",
        normal_prob=319.6,
        high_prob=31.9,
        normal_hit_dist=[
            Payout(balls=1500, weight=0.40, next_state="KAKUBEN"),
            Payout(balls=60, weight=0.20, next_state="KAKUBEN"),
            Payout(balls=1500, weight=0.40, next_state="JITAN", jitan_spins=100),
        ],
        st_hit_dist=[],
        jitan_hit_dist=[
            Payout(balls=1500, weight=0.01, next_state="JINBEE"),
            Payout(balls=1500, weight=0.51, next_state="KAKUBEN"),
            Payout(balls=60, weight=0.08, next_state="JINBEE"),
            Payout(balls=1500, weight=0.40, next_state="JITAN", jitan_spins=100),
        ],
        kakuben_hit_dist=[
            Payout(balls=1500, weight=0.01, next_state="JINBEE"),
            Payout(balls=1500, weight=0.51, next_state="KAKUBEN"),
            Payout(balls=60, weight=0.08, next_state="JINBEE"),
            Payout(balls=1500, weight=0.40, next_state="JITAN", jitan_spins=100),
        ],
        lt_hit_dist=[],
        jinbee_hit_dist=[
            Payout(balls=1500, weight=0.52, next_state="JINBEE"),
            Payout(balls=60, weight=0.08, next_state="JINBEE"),
            Payout(balls=1500, weight=0.40, next_state="JINBEE_JITAN", jitan_spins=200),
        ],
        simplification_notes="通常時 40% 10R確変/20% 2R確変/40% 10R通常. 電サポ中의 10R確変-A 1%와 2R確変 8%는 ジンベェタイム으로 분리.",
        spec_source="P-WORLD database/10321 / なな徹 / Pachiseven",
        confidence="high",
        notes="ジンベェタイム 중 通常当り 후 時短200을 JINBEE_JITAN 상태로 별도 모델링. 沖海3000BONUS 보류연 연출은 독립 당첨으로 처리.",
        is_estimated=False,
    ),

    # A-2. PAスーパー海物語 IN 沖縄5 with アイマリン (감데지)
    "oki_sea_5_imarine": Machine(
        id="oki_sea_5_imarine",
        name_ja="PAスーパー海物語 IN 沖縄5 with アイマリン",
        name_ko="PA 슈퍼 바다이야기 IN 오키나와5 with 아이마린",
        spec_type="감데지 / ST",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=9.9,
        normal_hit_dist=[
            Payout(balls=1100, weight=0.10, next_state='ST', st_spins=5, jitan_spins=95),
            Payout(balls=550, weight=0.57, next_state='ST', st_spins=5, jitan_spins=45),
            Payout(balls=550, weight=0.33, next_state='ST', st_spins=5, jitan_spins=20)
        ],
        st_hit_dist=[
            Payout(balls=1100, weight=0.10, next_state='ST', st_spins=5, jitan_spins=95),
            Payout(balls=550, weight=0.57, next_state='ST', st_spins=5, jitan_spins=45),
            Payout(balls=550, weight=0.33, next_state='ST', st_spins=5, jitan_spins=20)
        ],
        jitan_hit_dist=[
            Payout(balls=1100, weight=0.10, next_state='ST', st_spins=5, jitan_spins=95),
            Payout(balls=550, weight=0.57, next_state='ST', st_spins=5, jitan_spins=45),
            Payout(balls=550, weight=0.33, next_state='ST', st_spins=5, jitan_spins=20)
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="ST 5회 소진 시 자동으로 남은 jitan_spins 만큼 시단(JITAN) 상태로 전환되도록 구현.",
        spec_source="P-WORLD database/9421 / なな徹 / Pachiseven",
        confidence="high",
        notes="ヘソ・電チュー共通 10R 10% / 5R時短45 57% / 5R時短20 33%를 반영.",
        is_estimated=False,
    ),

    # A-2b. PAスーパー海物語 IN 沖縄5 夜桜超旋風 99ver. (감데지)
    "oki_sea_5_yozakura_99": Machine(
        id="oki_sea_5_yozakura_99",
        name_ja="PAスーパー海物語 IN 沖縄5 夜桜超旋風 99ver.",
        name_ko="PA 슈퍼 바다이야기 IN 오키나와5 밤벚꽃 초선풍 99버전",
        spec_type="감데지 / 1種2種 RUSH",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=3.99,
        normal_hit_dist=[
            Payout(balls=350, weight=0.50, next_state="ST", st_spins=8),
            Payout(balls=350, weight=0.50, next_state="NORMAL"),
        ],
        st_hit_dist=[
            Payout(balls=700, weight=0.10, next_state="ST", st_spins=8),
            Payout(balls=210, weight=0.90, next_state="ST", st_spins=8),
        ],
        jitan_hit_dist=[
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="初当り는 전부 5R이며 50%만 RUSH. RUSH는 6회+残保留2개를 8회로 합산하고, 오른쪽 10R 10%/3R 90%를 반영.",
        spec_source="P-WORLD database/9748 / DMM machines/4270 / Dechau",
        confidence="high",
        notes="1種2種의 V入賞 실패 가능성과 보류별 연출 차이는 모델링하지 않습니다.",
        is_estimated=False,
    ),

    # A-3. PA大海物語5ブラックLT99ver. (감데지 LT)
    "sea_5_black_lt": Machine(
        id="sea_5_black_lt",
        name_ja="PA大海物語5ブラックLT99ver.",
        name_ko="PA 대해물어5 블랙 LT 99버전",
        spec_type="감데지 / LT",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=41.0,
        normal_hit_dist=[
            Payout(balls=310, weight=0.70, next_state='ST', st_spins=39, ball_variance=0.03),
            Payout(balls=310, weight=0.30, next_state='NORMAL', counts_as_rush=False, ball_variance=0.03)
        ],
        st_hit_dist=[
            Payout(balls=820, weight=0.10, next_state='LT', st_spins=110, is_lt=True, ball_variance=0.03), # 10% LT 진입
            Payout(balls=820, weight=0.30, next_state='ST', st_spins=39, ball_variance=0.03),
            Payout(balls=310, weight=0.60, next_state='ST', st_spins=39, ball_variance=0.03)
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[
            Payout(balls=820, weight=0.40, next_state='LT', st_spins=110, is_lt=True, ball_variance=0.03),
            Payout(balls=310, weight=0.60, next_state='LT', st_spins=110, is_lt=True, ball_variance=0.03)
        ],
        simplification_notes="初当り는 전부 3R이며 70%가 ST. 일반 ST는 35회+残保留4개를 39회로 합산, ST 중 大当り는 8R LT 10% / 8R ST 30% / 3R ST 60%. LT는 공개 継続期待値 약93%에 맞춰 110회로 모델링.",
        spec_source="P-WORLD database/10197 / DMM machines/4735",
        confidence="high",
        notes="880/330払出은 예산 계산용 실전 근사 820/310발로 사용. LT 종료 후 잔보류 당첨의 일반 ST振分 예외는 보수적으로 제외.",
        is_estimated=False,
    ),
}

SEA_ADDITION_MACHINES = {
    # DMM-confirmed Umi / Sea family additions.
    "sea_5": sea_kakuhen_10r(
        "sea_5",
        "P大海物語5",
        "P 대해물어5",
        "DMMぱちタウン machines/4293",
        confidence="high",
    ),
    "sea_5_special": sea_kakuhen_loop(
        machine_id="sea_5_special",
        name_ja="P大海物語5スペシャル",
        name_ko="P 대해물어5 스페셜",
        source="P-WORLD database/10112 / DMMぱちタウン",
        normal_prob=319.6,
        high_prob=31.9,
        kakuhen_weight=0.54,
        normal_weight=0.46,
        balls=1500,
        risk_grade="1/319",
        normal_jitan_spins=100,
        jitan_normal_jitan_spins=200,
        kakuben_normal_jitan_spins=100,
        confidence="high",
        simplification_notes="ヘソ/電チュー共通 54%確変・46%通常. 時短/遊タイム中の通常当り後だけ 時短200으로 분리.",
        notes="1500払出은 예산 계산용 실전 근사 1400발로 사용. 遊タイム 950회 도달 후 時短350은 시작回転 입력 기능이 없어 미반영.",
    ),
    "sea_3r3": Machine(
        id="sea_3r3",
        name_ja="PA海物語3R3",
        name_ko="PA 바다이야기 3R3",
        spec_type="감데지 / 확변 루프",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=16.9,
        normal_hit_dist=[
            Payout(balls=1000, weight=0.05, next_state="KAKUBEN"),
            Payout(balls=500, weight=0.46, next_state="KAKUBEN"),
            Payout(balls=500, weight=0.49, next_state="JITAN", jitan_spins=40, counts_as_rush=False),
        ],
        st_hit_dist=[],
        jitan_hit_dist=[
            Payout(balls=1000, weight=0.05, next_state="KAKUBEN"),
            Payout(balls=500, weight=0.46, next_state="KAKUBEN"),
            Payout(balls=500, weight=0.49, next_state="JITAN", jitan_spins=40),
        ],
        kakuben_hit_dist=[
            Payout(balls=1000, weight=0.05, next_state="KAKUBEN"),
            Payout(balls=500, weight=0.46, next_state="KAKUBEN"),
            Payout(balls=500, weight=0.49, next_state="JITAN", jitan_spins=40),
        ],
        lt_hit_dist=[],
        simplification_notes="ヘソ・電チュー共通の確変51% 루프. 通常49%는 時短40회로 분리하고, 時短 중 확률은 저확률 1/99.9로 처리.",
        spec_source="Pachiseven machines/7162 / DMMぱちタウン machines/4795",
        confidence="high",
        notes="DMM 표기 출옥 490/990개와 Pachiseven 지급 500/1000개 차이는 지급 기준 500/1000으로 통일.",
        is_estimated=False,
    ),
    "sea_5_black_199": Machine(
        id="sea_5_black_199",
        name_ja="P大海物語5 ブラック",
        name_ko="P 대해물어5 블랙",
        spec_type="라이트미들 / ST + GOLDパールRUSH",
        risk_grade="1/199",
        normal_prob=199.8,
        high_prob=44.0,
        normal_hit_dist=[
            Payout(balls=420, weight=1.00, next_state="ST", st_spins=54, ball_variance=0.03),
        ],
        st_hit_dist=[
            Payout(balls=1400, weight=0.04, next_state="UPPER", st_spins=90, ball_variance=0.03),
            Payout(balls=1400, weight=0.46, next_state="ST", st_spins=54, ball_variance=0.03),
            Payout(balls=420, weight=0.50, next_state="ST", st_spins=54, ball_variance=0.03),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        upper_hit_dist=[
            Payout(balls=1400, weight=0.50, next_state="UPPER", st_spins=90, ball_variance=0.03),
            Payout(balls=420, weight=0.50, next_state="UPPER", st_spins=90, ball_variance=0.03),
        ],
        simplification_notes="初当り後は通常ST 50回+残保留4. ST中大当り의 4%만 GOLDパールRUSH(86回+残保留4)로 승격.",
        spec_source="P-WORLD database/9916 / P-WORLD news",
        confidence="high",
        notes="1500/450払出은 예산 계산용 실전 근사 1400/420발로 사용. GOLDパールRUSH는 LT가 아닌 상위ST로 집계하며, LT 진입률에는 포함하지 않습니다.",
        is_estimated=False,
    ),
    "sea_4_special_black": Machine(
        id="sea_4_special_black",
        name_ja="P大海物語4スペシャルBLACK",
        name_ko="P 대해물어4 스페셜 BLACK",
        spec_type="라이트미들 / ST",
        risk_grade="1/199",
        normal_prob=199.8,
        high_prob=40.6,
        normal_hit_dist=[
            Payout(balls=1400, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
            Payout(balls=700, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
            Payout(balls=420, weight=0.40, next_state="ST", st_spins=51, ball_variance=0.03),
        ],
        st_hit_dist=[
            Payout(balls=1400, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
            Payout(balls=700, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
            Payout(balls=420, weight=0.40, next_state="ST", st_spins=51, ball_variance=0.03),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="ST突入率100%, ST51회(전サポ50회)를 하나의 ST 상태로 모델링. 10R30% / 5R30% / 3R40%를 반영.",
        spec_source="Pachiseven machines/6278 / Dechau machine/545",
        confidence="high",
        notes="1500/750/450払出은 예산 계산용 실전 근사 1400/700/420발로 사용. 1회전만 잠복ST가 되는 전サポ50회 표기는 실전 체감상 ST51회 추첨으로 합산.",
        is_estimated=False,
    ),
    "sea_4_special": sea_kakuhen_loop(
        machine_id="sea_4_special",
        name_ja="P大海物語4スペシャル",
        name_ko="P 대해물어4 스페셜",
        source="P-WORLD database/9256 / Pachiseven machines/6165 / なな徹",
        normal_prob=319.6,
        high_prob=39.7,
        kakuhen_weight=0.52,
        normal_weight=0.48,
        balls=1500,
        risk_grade="1/319",
        normal_jitan_spins=100,
        jitan_normal_jitan_spins=120,
        kakuben_normal_jitan_spins=120,
        confidence="high",
        simplification_notes="ヘソ・電チュー共通 10R確変52% / 10R通常48%. 非電サポ通常後は時短100, 電サポ中通常後는 時短120으로 분리.",
        notes="1500払出은 예산 계산용 실전 근사 1400발로 사용. 遊タイム950회 도달 시 時短350은 시작 회전수 입력이 없어 미반영.",
    ),
    "sea_4_agnes": sea_st_jitan(
        machine_id="sea_4_agnes",
        name_ja="PA大海物語4スペシャル Withアグネス・ラム",
        name_ko="PA 대해물어4 스페셜 With 아그네스 램",
        source="Pachiseven machines/6204 / なな徹",
        normal_prob=99.9,
        high_prob=19.5,
        payout_rows=[
            (1080, 0.04, 10, 90),
            (648, 0.60, 10, 40),
            (432, 0.06, 10, 40),
            (432, 0.30, 10, 15),
        ],
        risk_grade="1/99",
        confidence="high",
        simplification_notes="ST10회 + 時短15/40/90회. 공개振分 10R4%, 6R60%, 4R6%/30%를 반영.",
        notes="1080/648/432払出은 예산 계산용 실전 근사 1000/600/400발로 사용. 遊タイム379회는 시작回転 입력이 없어 미반영.",
    ),
    "sea_extreme_japan": Machine(
        id="sea_extreme_japan",
        name_ja="P海物語 極JAPAN",
        name_ko="P 바다이야기 극 JAPAN",
        spec_type="미들 / 1種2種 ST",
        risk_grade="1/319",
        normal_prob=319.6,
        high_prob=73.9,
        normal_hit_dist=[
            Payout(balls=1500, weight=0.50, next_state="ST", st_spins=104),
            Payout(balls=1500, weight=0.50, next_state="ST", st_spins=24, counts_as_rush=False),
        ],
        st_hit_dist=[
            Payout(balls=3000, weight=0.20, next_state="ST", st_spins=104),
            Payout(balls=1500, weight=0.55, next_state="ST", st_spins=104),
            Payout(balls=300, weight=0.25, next_state="ST", st_spins=104),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="初回はロングST100+残保留4이 50%, ショートST20+残保留4이 50%. ショートST 중 당첨은 ロングST로 승격된다고 모델링.",
        spec_source="P-WORLD database/10219 / Pachiseven machines/7123",
        confidence="high",
        notes="極ノ刻 토털 돌입률은 직행50%와 極チャンス引き戻し를 시뮬에서 자연 발생시킵니다.",
        is_estimated=False,
    ),
    "sea_extreme_japan_naginami": Machine(
        id="sea_extreme_japan_naginami",
        name_ja="PA海物語 極JAPAN Withナギナミ",
        name_ko="PA 바다이야기 극 JAPAN With 나기나미",
        spec_type="감데지 / 1種2種 ST",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=56.2,
        normal_hit_dist=[
            Payout(balls=240, weight=0.50, next_state="ST", st_spins=74),
            Payout(balls=240, weight=0.50, next_state="ST", st_spins=20, counts_as_rush=False),
        ],
        st_hit_dist=[
            Payout(balls=1600, weight=0.05, next_state="ST", st_spins=74),
            Payout(balls=800, weight=0.70, next_state="ST", st_spins=74),
            Payout(balls=240, weight=0.25, next_state="ST", st_spins=74),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="初回은 ロングST70+残保留4 50%, ショートST16+残保留4 50%. 特図2는 1600個+α 5% / 800個 70% / 240個 25%, +α 상乗せ는 1600개 대표값으로 보수화.",
        spec_source="DMMぱちタウン machines/4899 / なな徹 machines/1054 / Pachiseven machines/7264",
        confidence="high",
        notes="DMM/なな徹의 約1600個+α 5%, 約800個 70%, 約240個 25% 振分을 반영. 火鈴連発ボーナス 추가 상乗せ는 별도 루프로 만들지 않고 1600개로 근사.",
        is_estimated=False,
    ),
    "shinsea_99": Machine(
        id="shinsea_99",
        name_ja="PA新海物語",
        name_ko="PA 신 바다이야기",
        spec_type="감데지 / ST+時短+C時短",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=9.9,
        normal_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="ST", st_spins=5, jitan_spins=678),
            Payout(balls=500, weight=0.06, next_state="ST", st_spins=5, jitan_spins=678),
            Payout(balls=500, weight=0.57, next_state="ST", st_spins=5, jitan_spins=45),
            Payout(balls=500, weight=0.33, next_state="ST", st_spins=5, jitan_spins=20),
        ],
        st_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="ST", st_spins=5, jitan_spins=678),
            Payout(balls=500, weight=0.06, next_state="ST", st_spins=5, jitan_spins=678),
            Payout(balls=500, weight=0.57, next_state="ST", st_spins=5, jitan_spins=45),
            Payout(balls=500, weight=0.33, next_state="ST", st_spins=5, jitan_spins=20),
        ],
        jitan_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="ST", st_spins=5, jitan_spins=678),
            Payout(balls=500, weight=0.06, next_state="ST", st_spins=5, jitan_spins=678),
            Payout(balls=500, weight=0.57, next_state="ST", st_spins=5, jitan_spins=45),
            Payout(balls=500, weight=0.33, next_state="ST", st_spins=5, jitan_spins=20),
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        normal_support_prob=199.8,
        normal_support_dist=[
            Payout(balls=0, weight=0.01, next_state="JITAN", jitan_spins=379, counts_as_rush=False),
            Payout(balls=0, weight=0.09, next_state="JITAN", jitan_spins=100, counts_as_rush=False),
            Payout(balls=0, weight=0.40, next_state="JITAN", jitan_spins=40, counts_as_rush=False),
            Payout(balls=0, weight=0.50, next_state="JITAN", jitan_spins=20, counts_as_rush=False),
        ],
        simplification_notes="通常時は大当り1/99.9와 C時短1/199.8을 독립 경쟁 이벤트로 추첨. C時短은 출옥 없는 時短20/40/100/379회로 처리.",
        spec_source="P-WORLD database/9652 / なな徹 / 1geki",
        confidence="high",
        notes="10R/일부5R 후 긴 전サポ는 ST5+時短299 후 遊タイム379까지 이어지는 실질 683회로 반영. 일반 시작回転 기반 遊タイム狙い는 별도 미반영.",
        is_estimated=False,
    ),
    "ginpara_mugen_99": Machine(
        id="ginpara_mugen_99",
        name_ja="PAギンギラパラダイス 夢幻カーニバル 強99ver.",
        name_ko="PA 긴기라 파라다이스 몽환 카니발 강99",
        spec_type="감데지 / 遊タイム付き 1種2種",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=37.9,
        normal_hit_dist=[
            Payout(balls=370, weight=0.49, next_state="ST", st_spins=19),
            Payout(balls=550, weight=0.49, next_state="ST", st_spins=19),
            Payout(balls=370, weight=0.01, next_state="ST", st_spins=49),
            Payout(balls=820, weight=0.01, next_state="ST", st_spins=49),
        ],
        st_hit_dist=[
            Payout(balls=370, weight=0.45, next_state="ST", st_spins=49),
            Payout(balls=370, weight=0.05, next_state="ST", st_spins=300),
            Payout(balls=820, weight=0.40, next_state="ST", st_spins=49),
            Payout(balls=820, weight=0.10, next_state="ST", st_spins=300),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="初当り 15/45회+残保留4, 오른쪽 45/296회+残保留4를 ST 회전수로 합산. 遊タイム은 시작回転 입력이 없어 미반영.",
        spec_source="Pachiseven machines/6470 / PachinkoVillage / すろぬー",
        confidence="high",
        notes="右打ち振分의 296회 비율은 공개 표기 조합으로 근사. 유타임狙い는 별도 현장 회전수 입력 기능 필요.",
        is_estimated=False,
    ),
    "mawarun_sea_4_agnes_119": sea_st_jitan(
        machine_id="mawarun_sea_4_agnes_119",
        name_ja="Pまわるん大海物語4スペシャル Withアグネス・ラム 119ver.",
        name_ko="P 마와룽 대해물어4 스페셜 With 아그네스 램 119",
        source="P-WORLD database/9419 / Dechau machine/584",
        normal_prob=119.8,
        high_prob=19.5,
        payout_rows=[
            (1300, 0.04, 10, 90),
            (780, 0.56, 10, 40),
            (520, 0.07, 10, 40),
            (520, 0.33, 10, 20),
        ],
        risk_grade="1/119",
        confidence="high",
        simplification_notes="ST10회 + 時短20/40/90회. 119ver. 공개振分 10R4%, 6R56%, 4R7%/33%를 반영.",
        notes="1300/780/520払出은 예산 계산용 실전 근사 1210/730/480발로 사용. 遊タイム450회는 시작回転 입력이 없어 미반영.",
    ),
    "oki_sea_5_yozakura": Machine(
        id="oki_sea_5_yozakura",
        name_ja="Pスーパー海物語 IN 沖縄5 夜桜超旋風",
        name_ko="P 슈퍼 바다이야기 IN 오키나와5 밤벚꽃 초선풍",
        spec_type="미들 / 1種2種 RUSH",
        risk_grade="1/319",
        normal_prob=319.68,
        high_prob=3.99,
        normal_hit_dist=[
            Payout(balls=700, weight=0.58, next_state="ST", st_spins=8),
            Payout(balls=300, weight=0.42, next_state="ST", st_spins=8),
        ],
        st_hit_dist=[
            Payout(balls=1000, weight=0.20, next_state="ST", st_spins=8),
            Payout(balls=300, weight=0.80, next_state="ST", st_spins=8),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="初当り後 RUSH 100%. RUSH는 6회+残保留2개를 8회로 합산, 오른쪽 10R 20%/3R 80% 반영.",
        spec_source="P-WORLD database/9625 / Dechau",
        confidence="high",
        notes="1種2種의 V入賞 실패 가능성과 보류별 연출 차이는 모델링하지 않습니다.",
        is_estimated=False,
    ),
}

SEA_TRAILING_MACHINES = {
    "sea_5_agnes": Machine(
        id="sea_5_agnes",
        name_ja="PA大海物語5 Withアグネス・ラム",
        name_ko="PA 대해물어5 With 아그네스 램",
        spec_type="감데지 / ST+時短+ハピネスチャンス",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=19.5,
        normal_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="UPPER", st_spins=10, jitan_spins=110, ball_variance=0.03),
            Payout(balls=600, weight=0.60, next_state="ST", st_spins=10, jitan_spins=40, ball_variance=0.03),
            Payout(balls=400, weight=0.06, next_state="ST", st_spins=10, jitan_spins=40, ball_variance=0.03),
            Payout(balls=400, weight=0.30, next_state="ST", st_spins=10, jitan_spins=15, ball_variance=0.03),
        ],
        st_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="UPPER", st_spins=10, jitan_spins=110, ball_variance=0.03),
            Payout(balls=600, weight=0.60, next_state="ST", st_spins=10, jitan_spins=40, ball_variance=0.03),
            Payout(balls=400, weight=0.06, next_state="ST", st_spins=10, jitan_spins=40, ball_variance=0.03),
            Payout(balls=400, weight=0.30, next_state="ST", st_spins=10, jitan_spins=15, ball_variance=0.03),
        ],
        jitan_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="UPPER", st_spins=10, jitan_spins=110, ball_variance=0.03),
            Payout(balls=600, weight=0.60, next_state="ST", st_spins=10, jitan_spins=40, ball_variance=0.03),
            Payout(balls=400, weight=0.06, next_state="ST", st_spins=10, jitan_spins=40, ball_variance=0.03),
            Payout(balls=400, weight=0.30, next_state="ST", st_spins=10, jitan_spins=15, ball_variance=0.03),
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        upper_hit_dist=[
            Payout(balls=1000, weight=0.04, next_state="UPPER", st_spins=10, jitan_spins=110, ball_variance=0.03),
            Payout(balls=600, weight=0.60, next_state="UPPER", st_spins=10, jitan_spins=110, ball_variance=0.03),
            Payout(balls=400, weight=0.36, next_state="UPPER", st_spins=10, jitan_spins=110, ball_variance=0.03),
        ],
        simplification_notes="10R後はハピネスチャンス(상위 전サポ120회)로 전이. ハピネスチャンス 중 대당첨은 라운드와 무관하게 다시 ST10+時短110으로 유지.",
        spec_source="P-WORLD database/9833 / DMMぱちタウン machines/4358 / なな徹 machines/567",
        confidence="high",
        notes="1080/648/432払出은 예산 계산용 실전 근사 1000/600/400발로 사용. 遊タイム299회는 시작回転 입력이 없어 미반영.",
        is_estimated=False,
    ),
    "mediterranean_2_89": Machine(
        id="mediterranean_2_89",
        name_ja="PAスーパー海物語IN地中海2",
        name_ko="PA 슈퍼 바다이야기 IN 지중해2",
        spec_type="感デジ / LT搭載 一種二種",
        risk_grade="1/89",
        normal_prob=89.8,
        high_prob=34.8,
        normal_hit_dist=[
            Payout(balls=480, weight=0.50, next_state="ST", st_spins=24),
            Payout(balls=320, weight=0.50, next_state="ST", st_spins=24),
        ],
        st_hit_dist=[
            Payout(balls=800, weight=0.02, next_state="LT", st_spins=100, is_lt=True),
            Payout(balls=480, weight=0.48, next_state="ST", st_spins=48),
            Payout(balls=320, weight=0.50, next_state="ST", st_spins=48),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[
            Payout(balls=800, weight=0.02, next_state="LT", st_spins=104, is_lt=True),
            Payout(balls=480, weight=0.48, next_state="LT", st_spins=104, is_lt=True),
            Payout(balls=320, weight=0.50, next_state="LT", st_spins=104, is_lt=True),
        ],
        simplification_notes="チャンスタイム은 20회+残保留4개, 地中海JOURNEY는 44회+残保留4개로 합산. PREMIUM VACATION(LT)은 100회+残保留4개를 104회로 합산.",
        spec_source="P-WORLD database/10055 / Dechau / 海まにあ",
        confidence="high",
        notes="PREMIUM VACATION 종료 후 残保留 당첨이 地中海JOURNEY振分으로 돌아가는 예외는 공개継続率 약95.2%에 맞춰 LT 104회 모델로 근사.",
        is_estimated=False,
    ),
}
