from machine_templates import (
    eva_breakthrough_st_jitan,
    eva_vst_split_entry,
    sea_kakuhen_10r,
    sea_kakuhen_loop,
    sea_st_jitan,
)
from machine_types import Machine, Payout

MACHINES = {
    # A-1. Pスーパー海物語IN沖縄6 (미들)
    "oki_sea_6": Machine(
        id="oki_sea_6",
        name_ja="Pスーパー海物語IN沖縄6",
        name_ko="P 슈퍼 바다이야기 IN 오키나와6",
        spec_type="미들 / 확변 루프 + ジンベェタイム",
        risk_grade="1/319",
        normal_prob=319.6,
        high_prob=31.9,
        normal_hit_dist=[
            Payout(balls=1500, weight=0.40, next_state="KAKUBEN"),
            Payout(balls=60, weight=0.20, next_state="KAKUBEN"),
            Payout(balls=1500, weight=0.40, next_state="JITAN", jitan_spins=100),
        ],
        st_hit_dist=[],
        jitan_hit_dist=[
            Payout(balls=1500, weight=0.01, next_state="JINBEE"),
            Payout(balls=1500, weight=0.51, next_state="KAKUBEN"),
            Payout(balls=60, weight=0.08, next_state="JINBEE"),
            Payout(balls=1500, weight=0.40, next_state="JITAN", jitan_spins=100),
        ],
        kakuben_hit_dist=[
            Payout(balls=1500, weight=0.01, next_state="JINBEE"),
            Payout(balls=1500, weight=0.51, next_state="KAKUBEN"),
            Payout(balls=60, weight=0.08, next_state="JINBEE"),
            Payout(balls=1500, weight=0.40, next_state="JITAN", jitan_spins=100),
        ],
        lt_hit_dist=[],
        jinbee_hit_dist=[
            Payout(balls=1500, weight=0.52, next_state="JINBEE"),
            Payout(balls=60, weight=0.08, next_state="JINBEE"),
            Payout(balls=1500, weight=0.40, next_state="JINBEE_JITAN", jitan_spins=200),
        ],
        simplification_notes="通常時 40% 10R確変/20% 2R確変/40% 10R通常. 電サポ中의 10R確変-A 1%와 2R確変 8%는 ジンベェタイム으로 분리.",
        spec_source="P-WORLD database/10321 / なな徹 / Pachiseven",
        confidence="high",
        notes="ジンベェタイム 중 通常当り 후 時短200을 JINBEE_JITAN 상태로 별도 모델링. 沖海3000BONUS 보류연 연출은 독립 당첨으로 처리.",
        is_estimated=False,
    ),

    # A-2. PAスーパー海物語 IN 沖縄5 with アイマリン (감데지)
    "oki_sea_5_imarine": Machine(
        id="oki_sea_5_imarine",
        name_ja="PAスーパー海物語 IN 沖縄5 with アイマリン",
        name_ko="PA 슈퍼 바다이야기 IN 오키나와5 with 아이마린",
        spec_type="감데지 / ST",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=9.9,
        normal_hit_dist=[
            Payout(balls=1100, weight=0.10, next_state='ST', st_spins=5, jitan_spins=95),
            Payout(balls=550, weight=0.33, next_state='ST', st_spins=5, jitan_spins=45),
            Payout(balls=550, weight=0.57, next_state='ST', st_spins=5, jitan_spins=20)
        ],
        st_hit_dist=[
            Payout(balls=1100, weight=0.10, next_state='ST', st_spins=5, jitan_spins=95),
            Payout(balls=550, weight=0.33, next_state='ST', st_spins=5, jitan_spins=45),
            Payout(balls=550, weight=0.57, next_state='ST', st_spins=5, jitan_spins=20)
        ],
        jitan_hit_dist=[
            Payout(balls=1100, weight=0.10, next_state='ST', st_spins=5, jitan_spins=95),
            Payout(balls=550, weight=0.33, next_state='ST', st_spins=5, jitan_spins=45),
            Payout(balls=550, weight=0.57, next_state='ST', st_spins=5, jitan_spins=20)
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="ST 5회 소진 시 자동으로 남은 jitan_spins 만큼 시단(JITAN) 상태로 전환되도록 구현.",
        spec_source="P-WORLD database/9421 / なな徹 / Pachiseven",
        confidence="high",
        notes="ヘソ・電チュー共通 10R 10% / 5R時短45 57% / 5R時短20 33%를 반영.",
        is_estimated=False,
    ),

    # A-2b. PAスーパー海物語 IN 沖縄5 夜桜超旋風 99ver. (감데지)
    "oki_sea_5_yozakura_99": Machine(
        id="oki_sea_5_yozakura_99",
        name_ja="PAスーパー海物語 IN 沖縄5 夜桜超旋風 99ver.",
        name_ko="PA 슈퍼 바다이야기 IN 오키나와5 밤벚꽃 초선풍 99버전",
        spec_type="감데지 / 1種2種 RUSH",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=3.99,
        normal_hit_dist=[
            Payout(balls=350, weight=0.50, next_state="ST", st_spins=8),
            Payout(balls=350, weight=0.50, next_state="NORMAL"),
        ],
        st_hit_dist=[
            Payout(balls=700, weight=0.10, next_state="ST", st_spins=8),
            Payout(balls=210, weight=0.90, next_state="ST", st_spins=8),
        ],
        jitan_hit_dist=[
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="初当り는 전부 5R이며 50%만 RUSH. RUSH는 6회+残保留2개를 8회로 합산하고, 오른쪽 10R 10%/3R 90%를 반영.",
        spec_source="P-WORLD database/9748 / DMM machines/4270 / Dechau",
        confidence="high",
        notes="1種2種의 V入賞 실패 가능성과 보류별 연출 차이는 모델링하지 않습니다.",
        is_estimated=False,
    ),

    # A-3. PA大海物語5ブラックLT99ver. (감데지 LT)
    "sea_5_black_lt": Machine(
        id="sea_5_black_lt",
        name_ja="PA大海物語5ブラックLT99ver.",
        name_ko="PA 대해물어5 블랙 LT 99버전",
        spec_type="감데지 / LT",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=41.0,
        normal_hit_dist=[
            Payout(balls=310, weight=0.70, next_state='ST', st_spins=39, ball_variance=0.03),
            Payout(balls=310, weight=0.30, next_state='NORMAL', counts_as_rush=False, ball_variance=0.03)
        ],
        st_hit_dist=[
            Payout(balls=820, weight=0.10, next_state='LT', st_spins=110, is_lt=True, ball_variance=0.03), # 10% LT 진입
            Payout(balls=820, weight=0.30, next_state='ST', st_spins=39, ball_variance=0.03),
            Payout(balls=310, weight=0.60, next_state='ST', st_spins=39, ball_variance=0.03)
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[
            Payout(balls=820, weight=0.40, next_state='LT', st_spins=110, is_lt=True, ball_variance=0.03),
            Payout(balls=310, weight=0.60, next_state='LT', st_spins=110, is_lt=True, ball_variance=0.03)
        ],
        simplification_notes="初当り는 전부 3R이며 70%가 ST. 일반 ST는 35회+残保留4개를 39회로 합산, ST 중 大当り는 8R LT 10% / 8R ST 30% / 3R ST 60%. LT는 공개 継続期待値 약93%에 맞춰 110회로 모델링.",
        spec_source="P-WORLD database/10197 / DMM machines/4735",
        confidence="high",
        notes="880/330払出은 예산 계산용 실전 근사 820/310발로 사용. LT 종료 후 잔보류 당첨의 일반 ST振分 예외는 보수적으로 제외.",
        is_estimated=False,
    ),

    # B-4. 新世紀エヴァンゲリオン〜未来への咆哮〜 (에바15 미들)
    "eva_15_roar": eva_vst_split_entry(
        machine_id="eva_15_roar",
        name_ja="新世紀エヴァンゲリオン〜未来への咆哮〜",
        name_ko="신세기 에반게리온 미래로의 포효 (에바15)",
        source="SANKYO collection/925 / DMMぱちタウン machines/4021 / GA 2021-10-07 T1Y sheet",
        normal_prob=319.7,
        high_prob=99.4,
        st_spins=163,
        jitan_spins=100,
        first_10r_weight=0.03,
        first_3r_st_weight=0.56,
        first_3r_jitan_weight=0.41,
        first_10r_balls=1400,
        first_3r_balls=420,
        right_balls=1400,
        risk_grade="1/319",
        spec_type="미들 / V-ST",
        confidence="high",
        simplification_notes=(
            "特図1 10R確変 3% / 3R確変 56% / 3R通常 41%. "
            "通常後 時短100 중 당첨 시 ST163으로 승격."
        ),
        notes=(
            "DMM/SANKYO는 우측 ALL1500個払出로 표기하지만 예산/체류시간 계산은 "
            "T1Y 근사 10R 1400발, 3R 420발을 사용. ST継続率 약81%는 ST163회 기준으로 검증. "
            "右打ち中의 잔존ヘソ特図1通常後 時短500 예외와 残保留4는 별도 상태로 모델링하지 않음."
        ),
    ),

    # B-5. P新世紀エヴァンゲリオン〜未来への咆哮〜PREMIUM MODEL (에바15 프리미엄 1/129)
    "eva_15_premium": eva_breakthrough_st_jitan(
        machine_id="eva_15_premium",
        name_ja="P新世紀エヴァンゲリオン〜未来への咆哮〜PREMIUM MODEL",
        name_ko="P 신세기 에반게리온 미래로의 포효 프리미엄 모델",
        source="DMMぱちタウン machines/4498 / P-WORLD database/9993 / なな徹",
        normal_prob=129.8,
        high_prob=35.7,
        direct_rush_weight=0.10,
        challenge_st_weight=0.54,
        challenge_jitan_weight=0.36,
        challenge_st_spins=30,
        challenge_jitan_spins=30,
        rush_st_spins=30,
        rush_jitan_spins=100,
        first_10r_balls=930,
        first_3r_balls=280,
        right_10r_balls=930,
        right_3r_balls=280,
        right_10r_weight=0.60,
        right_3r_weight=0.40,
        risk_grade="1/129",
        spec_type="라이트 / 돌파형 V-ST",
        confidence="high",
        simplification_notes=(
            "ヘソ 10%는 RUSH 직행, 54%는 ST30 챌린지, 36%는 時短30 챌린지. "
            "챌린지 중 당첨 시 RUSH(ST30+時短100)로 승격."
        ),
        notes=(
            "DMM/P-WORLD의 約1000/300個払出을 예산 계산용 실전 근사 930/280발로 사용. "
            "残保留4 引き戻し는 별도 보류 상태 없이 회전수/벤치마크에 흡수."
        ),
    ),

    # B-6. ぱちんこ シン・エヴァンゲリオン 129 LT ver. (신 에바 129 LT)
    "shin_eva_129_lt": Machine(
        id="shin_eva_129_lt",
        name_ja="ぱちんこ シン・エヴァンゲリオン 129 LT ver.",
        name_ko="P 신 에반게리온 129 LT 버전",
        spec_type="라이트 / 1種2種 LT",
        risk_grade="1/129",
        normal_prob=129.8, 
        high_prob=54.4,
        normal_hit_dist=[
            Payout(balls=930, weight=0.005, next_state="LT", st_spins=127, is_lt=True, ball_variance=0.03),
            Payout(balls=280, weight=0.500, next_state="ST", st_spins=64, ball_variance=0.03),
            Payout(balls=280, weight=0.495, next_state="NORMAL", counts_as_rush=False, ball_variance=0.03),
        ],
        st_hit_dist=[
            Payout(balls=930, weight=0.10, next_state="LT", st_spins=127, is_lt=True, ball_variance=0.03),
            Payout(balls=930, weight=0.90, next_state="ST", st_spins=64, ball_variance=0.03),
        ],
        jitan_hit_dist=[
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[
            Payout(balls=930, weight=1.00, next_state="LT", st_spins=127, is_lt=True, ball_variance=0.03)
        ],
        simplification_notes="ヘソ 0.5% LT 직행, 50.0% RUSH, 49.5% 통상. RUSH는 60회+残保留4개, LT는 123회+残保留4개로 합산.",
        spec_source="P-WORLD database/10206 / DMM machines/4736 / なな徹",
        confidence="high",
        notes="DMM의 約1000/300個払出을 예산 계산용 실전 근사 930/280발로 사용. RUSH 중 10% LT, LT 중 100% LT継続 분포 반영.",
        is_estimated=False,
    ),

    # B-7. e 新世紀エヴァンゲリオン ～はじまりの記憶～ (1/399)
    "eva_beginning": Machine(
        id="eva_beginning",
        name_ja="e新世紀エヴァンゲリオン ～はじまりの記憶～",
        name_ko="e 신세기 에반게리온 시작의 기억",
        spec_type="스마트 파친코 / 399 LT-ST",
        risk_grade="1/399",
        normal_prob=399.9,
        high_prob=99.6,
        normal_hit_dist=[
            Payout(balls=1400, weight=0.005, next_state="LT", st_spins=157, is_lt=True, ball_variance=0.03),
            Payout(balls=280, weight=0.500, next_state="LT", st_spins=157, is_lt=True, ball_variance=0.03),
            Payout(balls=280, weight=0.495, next_state="JITAN", jitan_spins=100, counts_as_rush=False, ball_variance=0.03),
        ],
        st_hit_dist=[],
        jitan_hit_dist=[
            Payout(balls=280, weight=1.00, next_state="LT", st_spins=157, is_lt=True, ball_variance=0.03),
        ],
        kakuben_hit_dist=[],
        lt_hit_dist=[
            Payout(balls=4480, weight=0.005, next_state="LT", st_spins=157, is_lt=True, ball_variance=0.03),
            Payout(balls=2240, weight=0.995, next_state="LT", st_spins=157, is_lt=True, ball_variance=0.03),
        ],
        simplification_notes="ST突入=LT로 분류. ヘソ는 0.5% 10R LT, 50.0% 2R LT, 49.5% 2R+時短100. 오른쪽은 8R×2=2400払出 중심, 0.5%만 8R×4로 근사.",
        spec_source="DMMぱちタウン machines/4894 / P-WORLD database/10353 / 777パチガブ / SANKYO",
        confidence="medium",
        notes="DMM 123難波店 1円に1台あり. チャージ込み大当り確率(約1/349.9)과 チャージ昇格은 별도 상태로 구현하지 않음. 1500/300/2400/4800払出은 예산 계산용 실전 근사 1400/280/2240/4480발로 사용.",
    ),

    # C-8. P Re:ゼロから始める異世界生活 鬼がかり 99ver. (리제로 99)
    "re_zero_99": Machine(
        id="re_zero_99",
        name_ja="P Re:ゼロから始める異世界生活 鬼がかり 99ver.",
        name_ko="P 리제로 귀신들린 99버전",
        spec_type="감데지 / ST",
        risk_grade="1/99",
        normal_prob=99.9,
        high_prob=79.9,
        normal_hit_dist=[
            Payout(balls=300, weight=0.50, next_state='ST', st_spins=104),
            Payout(balls=300, weight=0.50, next_state='NORMAL') 
        ],
        st_hit_dist=[
            Payout(balls=1800, weight=0.25, next_state='ST', st_spins=104),
            Payout(balls=900, weight=0.50, next_state='ST', st_spins=104),
            Payout(balls=300, weight=0.05, next_state='ST', st_spins=104),
            Payout(balls=0, weight=0.20, next_state='ST', st_spins=104),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="50%로 RUSH(ST104회) 진입. 電チュー는 1800/900/300/Re:Start를 실제 비율로 분리.",
        spec_source="P-WORLD database/10364 / Pachiseven",
        confidence="high",
        notes="Re:Start는 0발 ST 리셋으로 모델링.",
        is_estimated=False,
    ),

    # C-9. P Re:ゼロから始める異世界生活 鬼がかり 199ver. (리제로 199)
    "re_zero_199": Machine(
        id="re_zero_199",
        name_ja="P Re:ゼロから始める異世界生活 鬼がかり 199ver.",
        name_ko="P 리제로 귀신들린 199버전",
        spec_type="라이트미들 / ST",
        risk_grade="1/199",
        normal_prob=199.8,
        high_prob=105.9,
        normal_hit_dist=[
            Payout(balls=300, weight=0.55, next_state='ST', st_spins=144),
            Payout(balls=300, weight=0.45, next_state='NORMAL')
        ],
        st_hit_dist=[
            Payout(balls=3000, weight=0.40, next_state='ST', st_spins=144),
            Payout(balls=1500, weight=0.40, next_state='ST', st_spins=144),
            Payout(balls=0, weight=0.20, next_state='ST', st_spins=144),
        ],
        jitan_hit_dist=[],
        kakuben_hit_dist=[],
        lt_hit_dist=[],
        simplification_notes="55%로 RUSH(ST144회) 진입. 電チュー는 3000/1500/Re:Start를 실제 비율로 분리.",
        spec_source="P-WORLD database/10363 / なな徹",
        confidence="high",
        notes="Re:Start는 0발 ST 리셋으로 모델링.",
        is_estimated=False,
    )
}

MACHINES.update(
    {
        # DMM-confirmed Umi / Sea family additions.
        "sea_5": sea_kakuhen_10r(
            "sea_5",
            "P大海物語5",
            "P 대해물어5",
            "DMMぱちタウン machines/4293",
            confidence="high",
        ),
        "sea_5_special": sea_kakuhen_loop(
            machine_id="sea_5_special",
            name_ja="P大海物語5スペシャル",
            name_ko="P 대해물어5 스페셜",
            source="P-WORLD database/10112 / DMMぱちタウン",
            normal_prob=319.6,
            high_prob=31.9,
            kakuhen_weight=0.54,
            normal_weight=0.46,
            balls=1500,
            risk_grade="1/319",
            normal_jitan_spins=100,
            jitan_normal_jitan_spins=200,
            kakuben_normal_jitan_spins=100,
            confidence="high",
            simplification_notes="ヘソ/電チュー共通 54%確変・46%通常. 時短/遊タイム中の通常当り後だけ 時短200으로 분리.",
            notes="1500払出은 예산 계산용 실전 근사 1400발로 사용. 遊タイム 950회 도달 후 時短350은 시작回転 입력 기능이 없어 미반영.",
        ),
        "sea_3r3": Machine(
            id="sea_3r3",
            name_ja="PA海物語3R3",
            name_ko="PA 바다이야기 3R3",
            spec_type="감데지 / 확변 루프",
            risk_grade="1/99",
            normal_prob=99.9,
            high_prob=16.9,
            normal_hit_dist=[
                Payout(balls=1000, weight=0.05, next_state="KAKUBEN"),
                Payout(balls=500, weight=0.46, next_state="KAKUBEN"),
                Payout(balls=500, weight=0.49, next_state="JITAN", jitan_spins=40, counts_as_rush=False),
            ],
            st_hit_dist=[],
            jitan_hit_dist=[
                Payout(balls=1000, weight=0.05, next_state="KAKUBEN"),
                Payout(balls=500, weight=0.46, next_state="KAKUBEN"),
                Payout(balls=500, weight=0.49, next_state="JITAN", jitan_spins=40),
            ],
            kakuben_hit_dist=[
                Payout(balls=1000, weight=0.05, next_state="KAKUBEN"),
                Payout(balls=500, weight=0.46, next_state="KAKUBEN"),
                Payout(balls=500, weight=0.49, next_state="JITAN", jitan_spins=40),
            ],
            lt_hit_dist=[],
            simplification_notes="ヘソ・電チュー共通の確変51% 루프. 通常49%는 時短40회로 분리하고, 時短 중 확률은 저확률 1/99.9로 처리.",
            spec_source="Pachiseven machines/7162 / DMMぱちタウン machines/4795",
            confidence="high",
            notes="DMM 표기 출옥 490/990개와 Pachiseven 지급 500/1000개 차이는 지급 기준 500/1000으로 통일.",
            is_estimated=False,
        ),
        "sea_5_black_199": Machine(
            id="sea_5_black_199",
            name_ja="P大海物語5 ブラック",
            name_ko="P 대해물어5 블랙",
            spec_type="라이트미들 / ST + GOLDパールRUSH",
            risk_grade="1/199",
            normal_prob=199.8,
            high_prob=44.0,
            normal_hit_dist=[
                Payout(balls=420, weight=1.00, next_state="ST", st_spins=54, ball_variance=0.03),
            ],
            st_hit_dist=[
                Payout(balls=1400, weight=0.04, next_state="UPPER", st_spins=90, ball_variance=0.03),
                Payout(balls=1400, weight=0.46, next_state="ST", st_spins=54, ball_variance=0.03),
                Payout(balls=420, weight=0.50, next_state="ST", st_spins=54, ball_variance=0.03),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            upper_hit_dist=[
                Payout(balls=1400, weight=0.50, next_state="UPPER", st_spins=90, ball_variance=0.03),
                Payout(balls=420, weight=0.50, next_state="UPPER", st_spins=90, ball_variance=0.03),
            ],
            simplification_notes="初当り後は通常ST 50回+残保留4. ST中大当り의 4%만 GOLDパールRUSH(86回+残保留4)로 승격.",
            spec_source="P-WORLD database/9916 / P-WORLD news",
            confidence="high",
            notes="1500/450払出은 예산 계산용 실전 근사 1400/420발로 사용. GOLDパールRUSH는 LT가 아닌 상위ST로 집계하며, LT 진입률에는 포함하지 않습니다.",
            is_estimated=False,
        ),
        "sea_4_special_black": Machine(
            id="sea_4_special_black",
            name_ja="P大海物語4スペシャルBLACK",
            name_ko="P 대해물어4 스페셜 BLACK",
            spec_type="라이트미들 / ST",
            risk_grade="1/199",
            normal_prob=199.8,
            high_prob=40.6,
            normal_hit_dist=[
                Payout(balls=1400, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
                Payout(balls=700, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
                Payout(balls=420, weight=0.40, next_state="ST", st_spins=51, ball_variance=0.03),
            ],
            st_hit_dist=[
                Payout(balls=1400, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
                Payout(balls=700, weight=0.30, next_state="ST", st_spins=51, ball_variance=0.03),
                Payout(balls=420, weight=0.40, next_state="ST", st_spins=51, ball_variance=0.03),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="ST突入率100%, ST51회(전サポ50회)를 하나의 ST 상태로 모델링. 10R30% / 5R30% / 3R40%를 반영.",
            spec_source="Pachiseven machines/6278 / Dechau machine/545",
            confidence="high",
            notes="1500/750/450払出은 예산 계산용 실전 근사 1400/700/420발로 사용. 1회전만 잠복ST가 되는 전サポ50회 표기는 실전 체감상 ST51회 추첨으로 합산.",
            is_estimated=False,
        ),
        "sea_4_special": sea_kakuhen_loop(
            machine_id="sea_4_special",
            name_ja="P大海物語4スペシャル",
            name_ko="P 대해물어4 스페셜",
            source="P-WORLD database/9256 / Pachiseven machines/6165 / なな徹",
            normal_prob=319.6,
            high_prob=39.7,
            kakuhen_weight=0.52,
            normal_weight=0.48,
            balls=1500,
            risk_grade="1/319",
            normal_jitan_spins=100,
            jitan_normal_jitan_spins=120,
            kakuben_normal_jitan_spins=120,
            confidence="high",
            simplification_notes="ヘソ・電チュー共通 10R確変52% / 10R通常48%. 非電サポ通常後は時短100, 電サポ中通常後는 時短120으로 분리.",
            notes="1500払出은 예산 계산용 실전 근사 1400발로 사용. 遊タイム950회 도달 시 時短350은 시작 회전수 입력이 없어 미반영.",
        ),
        "sea_4_agnes": sea_st_jitan(
            machine_id="sea_4_agnes",
            name_ja="PA大海物語4スペシャル Withアグネス・ラム",
            name_ko="PA 대해물어4 스페셜 With 아그네스 램",
            source="Pachiseven machines/6204 / なな徹",
            normal_prob=99.9,
            high_prob=19.5,
            payout_rows=[
                (1080, 0.04, 10, 90),
                (648, 0.60, 10, 40),
                (432, 0.06, 10, 40),
                (432, 0.30, 10, 15),
            ],
            risk_grade="1/99",
            confidence="high",
            simplification_notes="ST10회 + 時短15/40/90회. 공개振分 10R4%, 6R60%, 4R6%/30%를 반영.",
            notes="1080/648/432払出은 예산 계산용 실전 근사 1000/600/400발로 사용. 遊タイム379회는 시작回転 입력이 없어 미반영.",
        ),
        "sea_extreme_japan": Machine(
            id="sea_extreme_japan",
            name_ja="P海物語 極JAPAN",
            name_ko="P 바다이야기 극 JAPAN",
            spec_type="미들 / 1種2種 ST",
            risk_grade="1/319",
            normal_prob=319.6,
            high_prob=73.9,
            normal_hit_dist=[
                Payout(balls=1500, weight=0.50, next_state="ST", st_spins=104),
                Payout(balls=1500, weight=0.50, next_state="ST", st_spins=24, counts_as_rush=False),
            ],
            st_hit_dist=[
                Payout(balls=3000, weight=0.20, next_state="ST", st_spins=104),
                Payout(balls=1500, weight=0.55, next_state="ST", st_spins=104),
                Payout(balls=300, weight=0.25, next_state="ST", st_spins=104),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="初回はロングST100+残保留4이 50%, ショートST20+残保留4이 50%. ショートST 중 당첨은 ロングST로 승격된다고 모델링.",
            spec_source="P-WORLD database/10219 / Pachiseven machines/7123",
            confidence="high",
            notes="極ノ刻 토털 돌입률은 직행50%와 極チャンス引き戻し를 시뮬에서 자연 발생시킵니다.",
            is_estimated=False,
        ),
        "sea_extreme_japan_naginami": Machine(
            id="sea_extreme_japan_naginami",
            name_ja="PA海物語 極JAPAN Withナギナミ",
            name_ko="PA 바다이야기 극 JAPAN With 나기나미",
            spec_type="감데지 / 1種2種 ST",
            risk_grade="1/99",
            normal_prob=99.9,
            high_prob=56.2,
            normal_hit_dist=[
                Payout(balls=240, weight=0.50, next_state="ST", st_spins=74),
                Payout(balls=240, weight=0.50, next_state="ST", st_spins=20, counts_as_rush=False),
            ],
            st_hit_dist=[
                Payout(balls=800, weight=0.05, next_state="ST", st_spins=74),
                Payout(balls=240, weight=0.95, next_state="ST", st_spins=74),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="初回은 ロングST70+残保留4 50%, ショートST16+残保留4 50%. ショートST 중 당첨은 ロングST로 승격.",
            spec_source="Pachiseven machines/7264 / なな徹",
            confidence="high",
            notes="P-WORLD/Pachiseven의 3R/10R 출옥 표기를 기준으로 10R 5%, 3R 95%를 반영.",
            is_estimated=False,
        ),
        "shinsea_99": Machine(
            id="shinsea_99",
            name_ja="PA新海物語",
            name_ko="PA 신 바다이야기",
            spec_type="감데지 / ST+時短+C時短",
            risk_grade="1/99",
            normal_prob=99.9,
            high_prob=9.9,
            normal_hit_dist=[
                Payout(balls=1000, weight=0.04, next_state="ST", st_spins=5, jitan_spins=678),
                Payout(balls=500, weight=0.06, next_state="ST", st_spins=5, jitan_spins=678),
                Payout(balls=500, weight=0.57, next_state="ST", st_spins=5, jitan_spins=45),
                Payout(balls=500, weight=0.33, next_state="ST", st_spins=5, jitan_spins=20),
            ],
            st_hit_dist=[
                Payout(balls=1000, weight=0.04, next_state="ST", st_spins=5, jitan_spins=678),
                Payout(balls=500, weight=0.06, next_state="ST", st_spins=5, jitan_spins=678),
                Payout(balls=500, weight=0.57, next_state="ST", st_spins=5, jitan_spins=45),
                Payout(balls=500, weight=0.33, next_state="ST", st_spins=5, jitan_spins=20),
            ],
            jitan_hit_dist=[
                Payout(balls=1000, weight=0.04, next_state="ST", st_spins=5, jitan_spins=678),
                Payout(balls=500, weight=0.06, next_state="ST", st_spins=5, jitan_spins=678),
                Payout(balls=500, weight=0.57, next_state="ST", st_spins=5, jitan_spins=45),
                Payout(balls=500, weight=0.33, next_state="ST", st_spins=5, jitan_spins=20),
            ],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            normal_support_prob=199.8,
            normal_support_dist=[
                Payout(balls=0, weight=0.01, next_state="JITAN", jitan_spins=379, counts_as_rush=False),
                Payout(balls=0, weight=0.09, next_state="JITAN", jitan_spins=100, counts_as_rush=False),
                Payout(balls=0, weight=0.40, next_state="JITAN", jitan_spins=40, counts_as_rush=False),
                Payout(balls=0, weight=0.50, next_state="JITAN", jitan_spins=20, counts_as_rush=False),
            ],
            simplification_notes="通常時は大当り1/99.9와 C時短1/199.8을 독립 경쟁 이벤트로 추첨. C時短은 출옥 없는 時短20/40/100/379회로 처리.",
            spec_source="P-WORLD database/9652 / なな徹 / 1geki",
            confidence="high",
            notes="10R/일부5R 후 긴 전サポ는 ST5+時短299 후 遊タイム379까지 이어지는 실질 683회로 반영. 일반 시작回転 기반 遊タイム狙い는 별도 미반영.",
            is_estimated=False,
        ),
        "ginpara_mugen_99": Machine(
            id="ginpara_mugen_99",
            name_ja="PAギンギラパラダイス 夢幻カーニバル 強99ver.",
            name_ko="PA 긴기라 파라다이스 몽환 카니발 강99",
            spec_type="감데지 / 遊タイム付き 1種2種",
            risk_grade="1/99",
            normal_prob=99.9,
            high_prob=37.9,
            normal_hit_dist=[
                Payout(balls=370, weight=0.49, next_state="ST", st_spins=19),
                Payout(balls=550, weight=0.49, next_state="ST", st_spins=19),
                Payout(balls=370, weight=0.01, next_state="ST", st_spins=49),
                Payout(balls=820, weight=0.01, next_state="ST", st_spins=49),
            ],
            st_hit_dist=[
                Payout(balls=370, weight=0.45, next_state="ST", st_spins=49),
                Payout(balls=370, weight=0.05, next_state="ST", st_spins=300),
                Payout(balls=820, weight=0.40, next_state="ST", st_spins=49),
                Payout(balls=820, weight=0.10, next_state="ST", st_spins=300),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="初当り 15/45회+残保留4, 오른쪽 45/296회+残保留4를 ST 회전수로 합산. 遊タイム은 시작回転 입력이 없어 미반영.",
            spec_source="Pachiseven machines/6470 / PachinkoVillage / すろぬー",
            confidence="high",
            notes="右打ち振分의 296회 비율은 공개 표기 조합으로 근사. 유타임狙い는 별도 현장 회전수 입력 기능 필요.",
            is_estimated=False,
        ),
        "mawarun_sea_4_agnes_119": sea_st_jitan(
            machine_id="mawarun_sea_4_agnes_119",
            name_ja="Pまわるん大海物語4スペシャル Withアグネス・ラム 119ver.",
            name_ko="P 마와룽 대해물어4 스페셜 With 아그네스 램 119",
            source="P-WORLD database/9419 / Dechau machine/584",
            normal_prob=119.8,
            high_prob=19.5,
            payout_rows=[
                (1300, 0.04, 10, 90),
                (780, 0.56, 10, 40),
                (520, 0.07, 10, 40),
                (520, 0.33, 10, 20),
            ],
            risk_grade="1/119",
            confidence="high",
            simplification_notes="ST10회 + 時短20/40/90회. 119ver. 공개振分 10R4%, 6R56%, 4R7%/33%를 반영.",
            notes="1300/780/520払出은 예산 계산용 실전 근사 1210/730/480발로 사용. 遊タイム450회는 시작回転 입력이 없어 미반영.",
        ),
        "oki_sea_5_yozakura": Machine(
            id="oki_sea_5_yozakura",
            name_ja="Pスーパー海物語 IN 沖縄5 夜桜超旋風",
            name_ko="P 슈퍼 바다이야기 IN 오키나와5 밤벚꽃 초선풍",
            spec_type="미들 / 1種2種 RUSH",
            risk_grade="1/319",
            normal_prob=319.68,
            high_prob=3.99,
            normal_hit_dist=[
                Payout(balls=700, weight=0.58, next_state="ST", st_spins=8),
                Payout(balls=300, weight=0.42, next_state="ST", st_spins=8),
            ],
            st_hit_dist=[
                Payout(balls=1000, weight=0.20, next_state="ST", st_spins=8),
                Payout(balls=300, weight=0.80, next_state="ST", st_spins=8),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="初当り後 RUSH 100%. RUSH는 6회+残保留2개를 8회로 합산, 오른쪽 10R 20%/3R 80% 반영.",
            spec_source="P-WORLD database/9625 / Dechau",
            confidence="high",
            notes="1種2種의 V入賞 실패 가능성과 보류별 연출 차이는 모델링하지 않습니다.",
            is_estimated=False,
        ),

        # Eva family additions.
        "shin_eva_type_rei": eva_vst_split_entry(
            machine_id="shin_eva_type_rei",
            name_ja="ぱちんこ シン・エヴァンゲリオン Type レイ",
            name_ko="P 신 에반게리온 Type 레이",
            source="DMMぱちタウン machines/4452 / P-WORLD / Pachiseven",
            normal_prob=319.7,
            high_prob=99.5,
            st_spins=163,
            jitan_spins=100,
            first_10r_weight=0.01,
            first_3r_st_weight=0.62,
            first_3r_jitan_weight=0.37,
            first_10r_balls=1400,
            first_3r_balls=280,
            right_balls=1400,
            risk_grade="1/319",
            spec_type="에바 / V-ST",
            confidence="high",
            simplification_notes=(
                "特図1 10R確変 1% / 3R確変 62% / 3R通常 37%. "
                "通常後 時短100 중 당첨 시 ST163으로 승격."
            ),
            notes=(
                "1500/300個払出 표기는 예산 계산용 실전 근사 1400/280발로 사용. "
                "高ベース中의 特図1通常当り 時短500 예외와 残保留4는 별도 상태로 모델링하지 않음."
            ),
        ),
        "shin_eva_premium_99": eva_breakthrough_st_jitan(
            machine_id="shin_eva_premium_99",
            name_ja="ぱちんこ シン・エヴァンゲリオン PREMIUM MODEL",
            name_ko="P 신 에반게리온 프리미엄 모델",
            source="DMMぱちタウン machines/4865 / P-WORLD database/10331",
            normal_prob=99.9,
            high_prob=37.5,
            direct_rush_weight=0.01,
            challenge_st_weight=0.58,
            challenge_jitan_weight=0.41,
            challenge_st_spins=30,
            challenge_jitan_spins=30,
            rush_st_spins=30,
            rush_jitan_spins=70,
            first_10r_balls=930,
            first_3r_balls=280,
            right_10r_balls=930,
            right_3r_balls=280,
            right_10r_weight=0.50,
            right_3r_weight=0.50,
            risk_grade="1/99",
            spec_type="감데지 / 돌파형 ST",
            confidence="high",
            simplification_notes=(
                "ヘソ 1%는 RUSH 직행, 58%는 ST30 챌린지, 41%는 時短30 챌린지. "
                "챌린지 중 당첨 시 RUSH(ST30+時短70)로 승격."
            ),
            notes=(
                "DMM/P-WORLD의 約1000/300個払出을 예산 계산용 실전 근사 930/280발로 사용. "
                "残保留4 引き戻し는 별도 보류 상태 없이 회전수/벤치마크에 흡수."
            ),
        ),
        "eva_15_special_199": eva_vst_split_entry(
            machine_id="eva_15_special_199",
            name_ja="P新世紀エヴァンゲリオン〜未来への咆哮〜SPECIAL EDITION",
            name_ko="P 에바15 스페셜 에디션 199",
            source="DMMぱちタウン / P-WORLD database/9892",
            normal_prob=199.2,
            high_prob=82.6,
            st_spins=135,
            jitan_spins=100,
            first_10r_weight=0.01,
            first_3r_st_weight=0.24,
            first_3r_jitan_weight=0.75,
            first_10r_balls=1020,
            first_3r_balls=300,
            right_balls=1020,
            risk_grade="1/199",
            spec_type="라이트미들 / 돌파형 V-ST",
            confidence="high",
            simplification_notes=(
                "特図1 10R確変 1% / 3R確変 24% / 3R通常 75%. "
                "通常後 時短100 중 당첨 시 ST135으로 승격."
            ),
            notes=(
                "1100/330個払出 표기는 예산 계산용 실전 근사 1020/300발로 사용. "
                "高ベース中의 特図1通常当り 時短200 예외와 残保留4는 별도 상태로 모델링하지 않음."
            ),
        ),

        # Re:Zero additions. User scope keeps non-Eva/Umi additions to Re:Zero only.
        "re_zero_319": Machine(
            id="re_zero_319",
            name_ja="P Re:ゼロから始める異世界生活 鬼がかりver.",
            name_ko="P 리제로 귀신들린 버전",
            spec_type="리제로 / 1種2種 RUSH",
            risk_grade="1/319",
            normal_prob=319.6,
            high_prob=99.9,
            normal_hit_dist=[
                Payout(balls=3000, weight=0.55, next_state="ST", st_spins=144),
                Payout(balls=1500, weight=0.45, next_state="NORMAL"),
            ],
            st_hit_dist=[
                Payout(balls=3000, weight=0.25, next_state="ST", st_spins=144),
                Payout(balls=1500, weight=0.55, next_state="ST", st_spins=144),
                Payout(balls=300, weight=0.06, next_state="ST", st_spins=144),
                Payout(balls=0, weight=0.14, next_state="ST", st_spins=144),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="通常時 3000発+RUSH 55% / 1500発通常 45%. RUSH中은 3000/1500/300/Re:Start 실제比率.",
            spec_source="P-WORLD database/9537 / Pachiseven / Dechau",
            confidence="high",
            notes="Re:Start는 0발 ST 리셋으로 모델링.",
            is_estimated=False,
        ),
        "re_zero_s2_349": Machine(
            id="re_zero_s2_349",
            name_ja="e Re:ゼロから始める異世界生活 season2",
            name_ko="e 리제로 시즌2",
            spec_type="스마트 파친코 / 1種2種 RUSH",
            risk_grade="1/349",
            normal_prob=349.9,
            high_prob=99.9,
            normal_hit_dist=[
                Payout(balls=3000, weight=0.55, next_state="ST", st_spins=145),
                Payout(balls=1500, weight=0.45, next_state="NORMAL"),
            ],
            st_hit_dist=[
                Payout(balls=3000, weight=0.25, next_state="ST", st_spins=145),
                Payout(balls=1500, weight=0.55, next_state="ST", st_spins=145),
                Payout(balls=300, weight=0.20, next_state="ST", st_spins=145),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="通常時 RUSH突入時は約3000発+α로 ST145, 非突入은約1500発通常. RUSH中은 3000/1500/300 실제比率.",
            spec_source="P-WORLD database/9931 / なな徹",
            confidence="high",
            notes="3000発+α의 추가上乗せ는 3000발 대표값으로 보수화.",
            is_estimated=False,
        ),
        "re_zero_s2_129": Machine(
            id="re_zero_s2_129",
            name_ja="P Re:ゼロから始める異世界生活 season2 129ver.",
            name_ko="P 리제로 시즌2 129버전",
            spec_type="라이트 / RUSH+LT 보너스",
            risk_grade="1/129",
            normal_prob=129.9,
            high_prob=99.9,
            normal_hit_dist=[
                Payout(balls=300, weight=0.50, next_state="ST", st_spins=120),
                Payout(balls=300, weight=0.50, next_state="NORMAL"),
            ],
            st_hit_dist=[
                Payout(balls=9000, weight=0.03225, next_state="ST", st_spins=120, is_lt=True),
                Payout(balls=6000, weight=0.02450, next_state="ST", st_spins=120, is_lt=True),
                Payout(balls=4500, weight=0.01850, next_state="ST", st_spins=120, is_lt=True),
                Payout(balls=3000, weight=0.02450, next_state="ST", st_spins=120, is_lt=True),
                Payout(balls=1800, weight=0.02525, next_state="ST", st_spins=120, is_lt=True),
                Payout(balls=1500, weight=0.12500, next_state="ST", st_spins=120),
                Payout(balls=750, weight=0.55000, next_state="ST", st_spins=120),
                Payout(balls=300, weight=0.20000, next_state="ST", st_spins=120),
            ],
            jitan_hit_dist=[],
            kakuben_hit_dist=[],
            lt_hit_dist=[],
            simplification_notes="RUSH 중 1500個 25% 중 절반을 LT 보너스로 분리. LT는 별도 전サポ 상태가 아니라 대량出玉 후 ST120으로 복귀하는 보너스로 모델링.",
            spec_source="P-WORLD database/10435 / P-WORLD news / Pachiseven",
            confidence="high",
            notes="超強欲PREMIUM BONUS의 300個 약 95% 루프는 공개 출玉帯 분포(9000/6000/4500/3000/1800+)로 근사.",
            is_estimated=False,
        ),
    }
)

MACHINES["hokuto_10"] = Machine(
    id="hokuto_10",
    name_ja="e北斗の拳10",
    name_ko="e 북두의 권 10",
    spec_type="스마트 파친코 / 전락형 LT",
    risk_grade="1/349",
    normal_prob=348.6,
    high_prob=40.0,
    normal_hit_dist=[
        Payout(balls=1500, weight=0.05, next_state="ST", st_spins=10000),
        Payout(balls=300, weight=0.70, next_state="ST", st_spins=10000),
        Payout(balls=300, weight=0.01, next_state="LT", st_spins=10000, is_lt=True),
        Payout(balls=300, weight=0.04, next_state="ST", st_spins=10000),
        Payout(balls=300, weight=0.20, next_state="NORMAL", counts_as_rush=False),
    ],
    st_hit_dist=[
        Payout(balls=1500, weight=0.126, next_state="LT", st_spins=10000, is_lt=True),
        Payout(balls=1500, weight=0.574, next_state="ST", st_spins=10000),
        Payout(balls=450, weight=0.300, next_state="ST", st_spins=10000),
    ],
    jitan_hit_dist=[],
    kakuben_hit_dist=[],
    lt_hit_dist=[
        Payout(balls=1500, weight=0.70, next_state="LT", st_spins=10000, is_lt=True),
        Payout(balls=450, weight=0.30, next_state="LT", st_spins=10000, is_lt=True),
    ],
    simplification_notes=(
        "BATTLE MODE/HYPER BATTLE MODE는 大当りor転落小当り까지인 전락형으로 모델링. "
        "전락 시 残保留4개引き戻し를 포함해 공개 継続率 약80%/약89%에 맞춥니다."
    ),
    spec_source="P-WORLD database/10054 / なな徹 / Pachiseven",
    confidence="high",
    notes=(
        "ヘソ 5% 10R+BATTLE, 70% 2R+BATTLE, 1% 2R+HYPER, 4% 2R+BATTLE, 20% 通常. "
        "BATTLE 중 10R의 약36%에서 無想転生チャンス, 그중 약50% 성공을 LT 전이 12.6%로 반영. "
        "世紀末チャージ(特図1小当り 約1/478)의 1% HYPER 루트는 보수적으로 별도 초당첨 확률에 합산하지 않음."
    ),
    is_estimated=False,
    fall_prob={"ST": 136.9, "LT": 275.9},
    fall_reserve_spins={"ST": 4, "LT": 4},
)

MACHINES["sea_5_agnes"] = sea_st_jitan(
    machine_id="sea_5_agnes",
    name_ja="PA大海物語5 Withアグネス・ラム",
    name_ko="PA 대해물어5 With 아그네스 램",
    source="P-WORLD database/9833 / DMMぱちタウン machines/4358",
    normal_prob=99.9,
    high_prob=19.5,
    payout_rows=[
        (1080, 0.04, 10, 110),
        (648, 0.60, 10, 40),
        (432, 0.06, 10, 40),
        (432, 0.30, 10, 15),
    ],
    risk_grade="1/99",
    confidence="high",
    simplification_notes="ST10회 + 時短15/40/110회. P-WORLD 공개振分(10R 4%, 6R 60%, 4R 6%/30%)을 반영.",
    notes="1080/648/432払出은 예산 계산용 실전 근사 1000/600/400발로 사용. ハピネスチャンス中 대당첨은 모두 120회 전サポ라는 예외는 별도 상태 없이 평균 분포로 근사.",
)
MACHINES["mediterranean_2_89"] = Machine(
    id="mediterranean_2_89",
    name_ja="PAスーパー海物語IN地中海2",
    name_ko="PA 슈퍼 바다이야기 IN 지중해2",
    spec_type="感デジ / LT搭載 一種二種",
    risk_grade="1/89",
    normal_prob=89.8,
    high_prob=34.8,
    normal_hit_dist=[
        Payout(balls=480, weight=0.50, next_state="ST", st_spins=24),
        Payout(balls=320, weight=0.50, next_state="ST", st_spins=24),
    ],
    st_hit_dist=[
        Payout(balls=800, weight=0.02, next_state="LT", st_spins=100, is_lt=True),
        Payout(balls=480, weight=0.48, next_state="ST", st_spins=48),
        Payout(balls=320, weight=0.50, next_state="ST", st_spins=48),
    ],
    jitan_hit_dist=[],
    kakuben_hit_dist=[],
    lt_hit_dist=[
        Payout(balls=800, weight=0.02, next_state="LT", st_spins=100, is_lt=True),
        Payout(balls=480, weight=0.48, next_state="LT", st_spins=100, is_lt=True),
        Payout(balls=320, weight=0.50, next_state="LT", st_spins=100, is_lt=True),
    ],
    simplification_notes="チャンスタイム은 20회+残保留4개, 地中海JOURNEY는 44회+残保留4개로 합산. PREMIUM VACATION(LT)은 공개 継続率 약94.5%에 맞춰 100회로 모델링.",
    spec_source="P-WORLD database/10055 / Dechau / 海まにあ",
    confidence="high",
    notes="PREMIUM VACATION 종료 후 残保留 당첨이 地中海JOURNEY振分으로 돌아가는 예외는 공개継続率에 맞춰 100회 모델로 보수화.",
    is_estimated=False,
)
