SESSION_TIME_LIMIT_HOURS = 11
SESSION_TIME_LIMIT_MINUTES = SESSION_TIME_LIMIT_HOURS * 60
LAST_CASH_INPUT_CUTOFF_HOURS = 10
LAST_CASH_INPUT_CUTOFF_MINUTES = LAST_CASH_INPUT_CUTOFF_HOURS * 60
STAY_HOUR_THRESHOLDS = tuple(range(1, SESSION_TIME_LIMIT_HOURS + 1))
