SESSION_TIME_LIMIT_HOURS = 9
SESSION_TIME_LIMIT_MINUTES = SESSION_TIME_LIMIT_HOURS * 60
HARD_SESSION_TIME_LIMIT_HOURS = 11
HARD_SESSION_TIME_LIMIT_MINUTES = HARD_SESSION_TIME_LIMIT_HOURS * 60
LAST_CASH_INPUT_CUTOFF_HOURS = 9
LAST_CASH_INPUT_CUTOFF_MINUTES = LAST_CASH_INPUT_CUTOFF_HOURS * 60
STAY_HOUR_THRESHOLDS = tuple(range(1, SESSION_TIME_LIMIT_HOURS + 1))
